config/routes.rb
Rails.application.routes.draw do
  resources :seatings
  resources :payments
  get 'show_times/new'
  get 'promotions/new'
  get 'promotion/new'
  get 'bookings/new'
  get 'halls/new'
  #post "movies/:id/edit"    => "movies#movieupdated"
  get '/bookmovie', to: 'movies#moviebooked'

  get 'password_resets/new'
  get 'password_resets/edit'
  root   'static_pages#home'
  get    '/signup',  to: 'users#new' 
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/users',   to:  'users#index'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :movies
  resources :halls
  resources :bookings
  resources :promotions
  resources :show_times
  resources :searches


end

app/models/seating.rb
class Seating < ApplicationRecord
end

app/controllers/seatings_controller.rb
class SeatingsController < ApplicationController
  before_action :set_seating, only: [:show, :edit, :update, :destroy]

  # GET /seatings
  # GET /seatings.json
  def index
    @seatings = Seating.all
  end

  # GET /seatings/1
  # GET /seatings/1.json
  def show
  end

  # GET /seatings/new
  def new
    @seating = Seating.new
  end

  # GET /seatings/1/edit
  def edit
  end

  # POST /seatings
  # POST /seatings.json
  def create
    @seating = Seating.new(seating_params)

    respond_to do |format|
      if @seating.save
        format.html { redirect_to @seating, notice: 'Seating was successfully created.' }
        format.json { render :show, status: :created, location: @seating }
      else
        format.html { render :new }
        format.json { render json: @seating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seatings/1
  # PATCH/PUT /seatings/1.json
  def update
    respond_to do |format|
      if @seating.update(seating_params)
        format.html { redirect_to @seating, notice: 'Seating was successfully updated.' }
        format.json { render :show, status: :ok, location: @seating }
      else
        format.html { render :edit }
        format.json { render json: @seating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seatings/1
  # DELETE /seatings/1.json
  def destroy
    @seating.destroy
    respond_to do |format|
      format.html { redirect_to seatings_url, notice: 'Seating was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seating
      @seating = Seating.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seating_params
      params.require(:seating).permit(:seat_row, :seat_no)
    end
end

app/helpers/seatings_helper.rb
module SeatingsHelper
end

app/views/seatings/_form.html.erb
<%= form_with(model: seating, local: true) do |form| %>
  <% if seating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(seating.errors.count, "error") %> prohibited this seating from being saved:</h2>

      <ul>
      <% seating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :seat_row %>
    <%= form.number_field :seat_row %>
  </div>

  <div class="field">
    <%= form.label :seat_no %>
    <%= form.number_field :seat_no %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/seatings/edit.html.erb
<h1>Editing Seating</h1>

<%= render 'form', seating: @seating %>

<%= link_to 'Show', @seating %> |
<%= link_to 'Back', seatings_path %>

app/views/seatings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Seatings</h1>

<table>
  <thead>
    <tr>
      <th>Seat row</th>
      <th>Seat no</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @seatings.each do |seating| %>
      <tr>
        <td><%= seating.seat_row %></td>
        <td><%= seating.seat_no %></td>
        <td><%= link_to 'Show', seating %></td>
        <td><%= link_to 'Edit', edit_seating_path(seating) %></td>
        <td><%= link_to 'Destroy', seating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Seating', new_seating_path %>

app/views/seatings/new.html.erb
<h1>New Seating</h1>

<%= render 'form', seating: @seating %>

<%= link_to 'Back', seatings_path %>

app/views/seatings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Seat row:</strong>
  <%= @seating.seat_row %>
</p>

<p>
  <strong>Seat no:</strong>
  <%= @seating.seat_no %>
</p>

<%= link_to 'Payment', controller: "payments", action: "new" %> |
<%= link_to 'Back', seatings_path %>