config/routes.rb
Rails.application.routes.draw do
  resources :seatings
  resources :payments
  get 'show_times/new'
  get 'promotions/new'
  get 'promotion/new'
  get 'bookings/new'
  get 'halls/new'
  #post "movies/:id/edit"    => "movies#movieupdated"
  get '/bookmovie', to: 'movies#moviebooked'

  get 'password_resets/new'
  get 'password_resets/edit'
  root   'static_pages#home'
  get    '/signup',  to: 'users#new' 
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/users',   to:  'users#index'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :movies
  resources :halls
  resources :bookings
  resources :promotions
  resources :show_times
  resources :searches


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
	  belongs_to :user
	    
	    belongs_to :movie 

	    belongs_to :show_time

end

app/models/hall.rb
class Hall < ApplicationRecord

   has_many :show_times   

end

app/models/movie.rb
class Movie < ApplicationRecord
   validates :name, presence: true, length: { maximum: 50 }

   validates :category, presence: true, length: { maximum: 50 }

   has_many :bookings

   has_many :show_times

  

   mount_uploader :avatar, AvatarUploader
   def self.search(search)
       if search
       	where(["name LIKE ?","%#{search}%"])
         		
         	else
         		all
         	end  	
   	
   end
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/promotion.rb
class Promotion < ApplicationRecord
end

app/models/search.rb
class Search < ApplicationRecord

	def search_movies

		movies = Movie.all

		movies = movies.where(["name LIKE ?","%#{keywords}%"]) if keywords.present?
		movies = movies.where(["category LIKE ?",category]) if category.present?

		return movies
	end

	

end

app/models/seating.rb
class Seating < ApplicationRecord
end

app/models/show_time.rb
class ShowTime < ApplicationRecord

	belongs_to :movie

	 belongs_to :hall
end

app/models/user.rb
class User < ApplicationRecord

  has_many :bookings

    attr_accessor :remember_token, :activation_token, :reset_token
  before_save   :downcase_email
  before_create :create_activation_digest

  #validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence:   true, length: { maximum: 255 },
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

                  
# Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

   # Returns a random token.
 
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # Remembers a user in the database for use in persistent sessions.
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

# Returns true if the given token matches the digest.
  
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

# Forgets a user.

  def forget
    update_attribute(:remember_digest, nil)
  end


## Activates an account.
  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
end

  # Sends activation email.
  def send_activation_email
   UserMailer.account_activation(self).deliver_now!
  end

  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
    end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end
  
  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  private

    # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
    end

    # Creates and assigns the activation token and digest.
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/halls_helper.rb
module HallsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/promotions_helper.rb
module PromotionsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/seatings_helper.rb
module SeatingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end


# Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end

  # Returns the current logged-in user (if any).
  
  def current_user
        if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
            if user && user.authenticated?(:remember, cookies[:remember_token])

        log_in user
        @current_user = user
      end
    end
 end
 
 # Returns true if the user is logged in, false otherwise.
 
  def logged_in?
    !current_user.nil?
  end
 
  # Forgets a persistent session.
  
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
 
 # Logs out the current user.
 
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

 # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end

  
end

app/helpers/show_times_helper.rb
module ShowTimesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.firstname, class: "gravatar")
  end
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

    <h1>About</h1>
    <p>
      The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
      Tutorial</em></a> is a
      <a href="http://www.railstutorial.org/book">book</a> and
      <a href="http://screencasts.railstutorial.org/">screencast series</a>
      to teach web development with
      <a href="http://rubyonrails.org/">Ruby on Rails</a>.
      This is the sample application for the tutorial.
    </p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

    <h1>Help</h1>
    <p>
      Get help on the Ruby on Rails Tutorial at the
      <a href="http://www.railstutorial.org/help">Rails Tutorial help
      section</a>.
      To get help on this sample app, see the
      <a href="http://www.railstutorial.org/book"><em>Ruby on Rails
      Tutorial</em> book</a>.
    </p>
 

app/views/static_pages/home.html.erb
<% provide(:title, "BookNow") %>

<div class="container-fluid">

         <div id="myCarousel" class="carousel slide" data-ride="carousel">
             <!-- Indicators -->
              <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <li data-target="#myCarousel" data-slide-to="2"></li>
              </ol>

                        <!-- Wrapper for slides -->
                          <div class="carousel-inner">
                               <div class="item active">
                                        <img src="/assets/infinitywar.jpg" alt="Avengersinfinitywar" style="width:100%;">
                               </div>

                               <div class="item">
                                         <img src="/assets/JSLeague.jpg" alt="Justice League" style="width:100%;">
                               </div>
    
                                <div class="item">
                                         <img src="/assets/venombig.jpg" alt="venom" style="width:100%;">
                                </div>
    					   </div>

                               <!-- Left and right controls -->
                                  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                                          <span class="glyphicon glyphicon-chevron-left"></span>
                                          <span class="sr-only">Previous</span>
                                   </a>
                                  
                                  <a class="right carousel-control" href="#myCarousel" data-slide="next">
                                           <span class="glyphicon glyphicon-chevron-right"></span>
                                           <span class="sr-only">Next</span>
                                  </a>
         </div>
    </div>
    <br></br>

    <div class=" center jumbotron">
    	 
  <h1>Welcome to Book Now</h1>

  <h2>
    You can Register for free on our website.Hurry!!
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
      
   </div>
                       <H1><strong>Now Playing</strong></H1>
                       <hr></hr>
                       
                        <%= link_to 'View All', movies_path, class: "view-all" %>
                      
                       </br></br>
                             <div class="container">
                                 <div class="row">

                                   <div class="col-sm-4">
                                          <figure class="figure">
  <img src="/assets/aviw.jpg" class="figure-img img-fluid rounded" alt="">
  <figcaption class="figure-caption"><a href="/bookmovie" class="btn btn-success">Book Now</a>
    <button class="btn btn-primary pull-right">View Rating</button></figcaption>
</figure></div>
                                     
                                     <div class="col-sm-4">
                                     	<figure class="figure">
  <img src="/assets/venom.jpg" class="figure-img img-fluid rounded" alt="">
  <figcaption class="figure-caption"><button class="btn btn-success">Book Now</button><button class="btn btn-primary pull-right">View Rating</button></figcaption></figcaption>
</figure></div>
                                         <div class="col-sm-4">
                                      <figure class="figure">
  <img src="/assets/smallfoot.jpg" class="figure-img img-fluid rounded" alt="smallfoot">
  <figcaption class="figure-caption"><button class="btn btn-success">Book Now</button><button class="btn btn-primary pull-right">View Rating</button></figcaption></figcaption>
</figure></div>
                                  </div>
                                </div>
                             	 
<hr></hr>
<br><br>
<br></br>
                       


                     <H1><strong>Coming Soon</strong></H1>
                     <hr></hr>
                        <a href="..." class="view-all" >View All</a>
                        </br></br>
                             <div class="container">
                                 <div class="row">
                                     <div class="col-sm-4">
                                     	<figure class="figure">
  <img src="/assets/spiderman.jpg" class="figure-img img-fluid rounded" alt="spiderman">
 
</figure></div>
                                     <div class="col-sm-4">
                                     	<figure class="figure">
  <img src="/assets/bohemian.jpg" class="figure-img img-fluid rounded" alt="bohemian">
</figure></div>
                                         <div class="col-sm-4">
                                         	<figure class="figure">
  <img src="/assets/aquaman.jpg" class="figure-img img-fluid rounded" alt="aquaman">
</figure></div>
                                  </div>
                                </div>
 <hr></hr>
<br><br><br><br><br>

                      <H1><strong>News</strong></H1>
                      <hr></hr>
                        <a href="..." class="view-all" >View All</a>
                        </br></br>
                             <div class="container">
                                 <div class="row">
                                     <div class="col-sm-4">
                                     	<figure class="figure">
  <img src="/assets/Cap.jpg" class="figure-img img-fluid rounded" alt="darkknight">
  <figcaption class="figure-caption"><h3><b>Chris Evans Hints His Captain America Days Are Over With Avengers 4 Wrap Tweet.</h3></b>
  </figcaption>	
</figure></div>
                                     <div class="col-sm-4">
                                     	<figure class="figure">
  <img src="/assets/chrispratt.jpg" class="figure-img img-fluid rounded" alt="">
  <figcaption class="figure-caption"><h3><b>Chris Pratt confirmed starting shooting for Avengers 2019</b></h3></figcaption>
</figure></div>
                                         <div class="col-sm-4">
                                         	<figure class="figure">
  <img src="/assets/kevin-hart.jpg" class="figure-img img-fluid rounded" alt="">
  <figcaption class="figure-caption"><h3><b>Kevin Hart's new movies becomes U.S. number 1 movie</b></h3></figcaption>
</figure></div>
                                  </div>
                                
                                <br><br>