config/routes.rb
Rails.application.routes.draw do
  resources :seatings
  resources :payments
  get 'show_times/new'
  get 'promotions/new'
  get 'promotion/new'
  get 'bookings/new'
  get 'halls/new'
  #post "movies/:id/edit"    => "movies#movieupdated"
  get '/bookmovie', to: 'movies#moviebooked'

  get 'password_resets/new'
  get 'password_resets/edit'
  root   'static_pages#home'
  get    '/signup',  to: 'users#new' 
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/users',   to:  'users#index'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :movies
  resources :halls
  resources :bookings
  resources :promotions
  resources :show_times
  resources :searches


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
	  belongs_to :user
	    
	    belongs_to :movie 

	    belongs_to :show_time

end

app/models/hall.rb
class Hall < ApplicationRecord

   has_many :show_times   

end

app/models/movie.rb
class Movie < ApplicationRecord
   validates :name, presence: true, length: { maximum: 50 }

   validates :category, presence: true, length: { maximum: 50 }

   has_many :bookings

   has_many :show_times

  

   mount_uploader :avatar, AvatarUploader
   def self.search(search)
       if search
       	where(["name LIKE ?","%#{search}%"])
         		
         	else
         		all
         	end  	
   	
   end
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/promotion.rb
class Promotion < ApplicationRecord
end

app/models/search.rb
class Search < ApplicationRecord

	def search_movies

		movies = Movie.all

		movies = movies.where(["name LIKE ?","%#{keywords}%"]) if keywords.present?
		movies = movies.where(["category LIKE ?",category]) if category.present?

		return movies
	end

	

end

app/models/seating.rb
class Seating < ApplicationRecord
end

app/models/show_time.rb
class ShowTime < ApplicationRecord

	belongs_to :movie

	 belongs_to :hall
end

app/models/user.rb
class User < ApplicationRecord

  has_many :bookings

    attr_accessor :remember_token, :activation_token, :reset_token
  before_save   :downcase_email
  before_create :create_activation_digest

  #validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence:   true, length: { maximum: 255 },
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

                  
# Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

   # Returns a random token.
 
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # Remembers a user in the database for use in persistent sessions.
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

# Returns true if the given token matches the digest.
  
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

# Forgets a user.

  def forget
    update_attribute(:remember_digest, nil)
  end


## Activates an account.
  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
end

  # Sends activation email.
  def send_activation_email
   UserMailer.account_activation(self).deliver_now!
  end

  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
    end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end
  
  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  private

    # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
    end

    # Creates and assigns the activation token and digest.
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/halls_helper.rb
module HallsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/promotions_helper.rb
module PromotionsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/seatings_helper.rb
module SeatingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end


# Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end

  # Returns the current logged-in user (if any).
  
  def current_user
        if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
            if user && user.authenticated?(:remember, cookies[:remember_token])

        log_in user
        @current_user = user
      end
    end
 end
 
 # Returns true if the user is logged in, false otherwise.
 
  def logged_in?
    !current_user.nil?
  end
 
  # Forgets a persistent session.
  
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
 
 # Logs out the current user.
 
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

 # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end

  
end

app/helpers/show_times_helper.rb
module ShowTimesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.firstname, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
   <div class="panel panel-default">
                       <div class="panel-footer" align="center">Copyright BookNow.com. All Rights Reserved.</div>
                    </div>
  </nav>
</footer>

app/views/layouts/_header.html.erb

<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Book Now", root_path, id: "logo" %>
    <nav>
                   
         <%= form_tag movies_path, :method => 'get' do %>
         <%= text_field_tag :search, params[:search] %>
         <%= submit_tag "Search" %>
         <% end %>

         <%= link_to "Advanced Search", new_search_path %>


          <%# <ul class="nav navbar-nav  ml-auto mr-auto ">
          <form class="form-inline" id="search"><br>
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
               <button class="btn btn-warning my-2 my-sm-0" type="submit">
                <span class="glyphicon glyphicon-search"></span> Search
              </button>
           </form>
         </ul>
         <%# %>
                            

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Movies", movies_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "Halls", halls_path %></li>
          
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", edit_user_path(current_user) %></li>
              
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </div>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
     <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <%= render 'layouts/header' %>
    <div class="container">
            <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <%= yield %>
      <%= render 'layouts/footer' %>
      
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>